version: "3.9"
services:
  redis:
    image: redis:7
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports: ["9000:9000","9001:9001"]
    volumes: [ "minio-data:/data" ]
    restart: unless-stopped

  api:
    build: ./srv
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    environment:
      REDIS_URL: redis://redis:6379/0
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio12345
      MINIO_BUCKET: jobs
      SHARED_DIR: /shared
      MINIO_PUBLIC_URL: http://192.168.29.131:9000   # 👈 URL pública para descargas
    volumes:
      - ./srv:/app
      - shared-tmp:/shared
    depends_on: [ redis, minio ]
    ports: ["8000:8000"]
    restart: unless-stopped

  worker:
    build: ./srv
    command: celery -A worker.celery worker --loglevel=INFO --concurrency=2
    environment:
      REDIS_URL: redis://redis:6379/0
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio12345
      MINIO_BUCKET: jobs
      SHARED_DIR: /shared
      MINIO_PUBLIC_URL: http://192.168.29.131:9000   # 👈 igual aquí
    volumes:
      - ./srv:/app
      - shared-tmp:/shared
    depends_on: [ api, redis, minio ]
    restart: unless-stopped

volumes:
  minio-data:
  shared-tmp:
